export const configActions = {
    CONFIG_HAVE_CPU: 'CONFIG_HAVE_CPU',
    CONFIG_HAVE_MOTHERBOARD: 'CONFIG_HAVE_MOTHERBOARD',
    CONFIG_HAVE_RAM: 'CONFIG_HAVE_RAM',
    CONFIG_HAVE_GPU: 'CONFIG_HAVE_GPU',
    CONFIG_HAVE_SSD: 'CONFIG_HAVE_SSD',
    
}